### PR TITLE
Enhancement PR

### PR DESCRIPTION
**Pull request by Gjacquenot**
This PR does the following things

- Performed typo refactoring in pyx files
- Updated to newer Embree API (2.) . Embree 3.0 is being developed...
- Added the possibility to export all embree results when performing request
- Added 12 new tests run from nosetests, activated them in travis
- Run examples in travis

One can discuss each point...

### CODE REVIEW

**Comment by Gjacquenot** [comment]
@scopatz : We can look together to integrate this pull request.

**Comment by scopatz** [comment]
Hi @Gjacquenot - sorry for taking so long to get to this!  Thanks so much for the change. Do you want to have push rights to the repo so that this doesn't happen in the future?

**Comment by scopatz** [comment]
I can also issue a release with this change, if you want

**Comment by mikedh** [comment]
Hey thanks for this package, and maintaining it! Updates look great too. I noticed trimesh tests started failing after this update, with this message:

```
ERROR: test_rays (__main__.RayTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_ray.py", line 16, in test_rays
    hit_any.append(m.ray.intersects_any(**rays[name]))
  File "/home/mikedh/trimesh/trimesh/ray/ray_pyembree.py", line 227, in intersects_any
    ray_directions=ray_directions)
  File "/home/mikedh/trimesh/trimesh/ray/ray_pyembree.py", line 206, in intersects_first
    triangle_index = self._scene.run(ray_origins, ray_directions)
  File "pyembree/rtcore_scene.pyx", line 34, in pyembree.rtcore_scene.EmbreeScene.run
ValueError: Buffer dtype mismatch, expected 'float32_t' but got 'double'
```

It's not a problem for me, I just switched all arguments in trimesh from numpy `float64` to `float32` and it's working fine (https://github.com/mikedh/trimesh/commit/ab86f268aa51af3ed082b17b3e53f5706be6a80a). It may confuse people coming in however. 

What numpy does in their internal functions, and I've started doing in trimesh, is wrapping input args with something like:
`normals = np.asanyarray(normals, dtype=np.float32)`

**Comment by scopatz** [comment]
Thanks for bringing this up! Please feel free to put in any PRs to change the behavior if you think it is needed.

**Comment by Gjacquenot** [comment]
As Embree works only with 32 bit, it seemed to me important that user knows about it.

@mikedh , they are new output for intersection queries: a dict can be output `('u', 'v', 'Ng', 'tfar', 'primID', 'geomID')`. It could be exported in `trimesh`

**Comment by mikedh** [comment]
Cool yeah it's good to match the embree types then. I'll try to PR the `np.asanyarray` on inputs for backwards compatibility and robustness. 

Re: output dict, nice! I'll take a look at using it in the trimesh pyembree wrapper.

**Pull request merged**
